### ISSUE TITLE
Look into "cookies banner"

### ISSUE THREAD

**Issue by amreenp7** [unicef/publicgoods-roadmap#109]
- informational banner
- opt in or out banner 
- text for this banner (likely info banner)

**Comment by amreenp7** [comment]
- [X] VGS to reach out to Sanna re: unicef's privacy policy copy
- [x] Search up GDPR compliance with Google Anaytics
- [ ] Create an info banner
- [ ] Create a new page with Privacy Policy and Terms of Use

**Comment by amreenp7** [comment]
GDPR Compliance Notes: https://docs.google.com/document/d/1Zcm69aYwUATJua3kZvJCLskW4EAOP5Ant601FXSjvlc/edit

**Comment by lacabra** [comment]
I argue that this can be closed since we switched Web Analytics to CloudFlare, and we don't use cookies anymore.

**Comment by amreenp7** [comment]
Sounds good!
