### ISSUE TITLE
Kindly Plan for the next 2 quarters

### ISSUE THREAD

**Issue by amreenp7** [unicef/publicgoods-roadmap#113]
Plan for next two quarters including:
- OKRs (objectives)
- Proposed workstreams (and tasks)

**Comment by amreenp7** [comment]
Aim to present to the team on Thurs/Friday

**Comment by amreenp7** [comment]
https://docs.google.com/document/d/1pgvSH5r9U8oXJD9DMo52PDe_zoNY1IzHeyT8Cx495gc/edit#

Part 2 meeting happening on Thurs

**Comment by amreenp7** [comment]
Will be presented on Tues

**Comment by amreenp7** [comment]
@nathanfletcher - per Victor's feedback to breakdown the objectives, can you please add the numbers for each metric HERE?https://docs.google.com/spreadsheets/d/1lflcLhr6FGKyZCT05w849J_5OdO7KmIJK_w4V4GG-_c/edit#gid=844115826

**Comment by amreenp7** [comment]
NF to input objectives and tasks by EOD Jan 10

**Comment by amreenp7** [comment]
Amreen and NF to update based on feedback by EOD Jan 14

**Comment by lacabra** [comment]
I consider this work done. Closing.
