### ISSUE TITLE
Implementation Dashboard Idea

### ISSUE THREAD

**Issue by amreenp7** [unicef/publicgoods-roadmap#118]
- Write up on the Implementation Dashboard Idea (https://docs.google.com/document/d/1pgvSH5r9U8oXJD9DMo52PDe_zoNY1IzHeyT8Cx495gc/edit)

- Add to this document: https://docs.google.com/document/d/1tS6XMDCMV1F_vTOvF2MUuQiP7sLkclOQ167qXGsmKcM/edit

**Comment by amreenp7** [comment]
Added concept note on "implementation map visualization" here: https://docs.google.com/document/d/1tS6XMDCMV1F_vTOvF2MUuQiP7sLkclOQ167qXGsmKcM/edit#heading=h.mz0gsbpam0ag

@lacabra @nathanbaleeta @nathanfletcher - please let me know your feedback when you get a chance to review it

**Comment by lacabra** [comment]
Reviewed, looks good so far.
