### ISSUE TITLE
Kindly Website Additions/Edits

### ISSUE THREAD

**Issue by amreenp7** [unicef/publicgoods-roadmap#120]
- [x] Add copy for privacy policy and terms of use
- [x] Update prompts

**Comment by amreenp7** [comment]
Updated prompts: https://docs.google.com/document/d/1tDQQHHlExhRCTPV2oLiph6Ss7pF3Uyv6aN2EEQH37Rc/edit

**Comment by amreenp7** [comment]
Privacy Policy and Terms of Use here: https://docs.google.com/document/d/1_GHA3W6gGuWE3zMHGmtFnIETwmxF7JaS9LVvU-yAbzM/edit?usp=sharing

Sabine, perhaps don't create a page for this until we get approval from any other internal stakeholders. It might be easier to finalize the copy over a Word doc or Google before transferring it over to the website.

**Comment by lacabra** [comment]
@amreenp7: I have reviewed the prompts. Once the team agrees on all of them, they can be updated by updating [this piece](https://github.com/unicef/kindly-website/blob/0556e79a3b1393a55df68e46cd663990a4d40b91/src/components/KindlyForm.js#L16) of the code.

**Comment by lacabra** [comment]
@amreenp7 I have reviewed the privacy policy and terms of service draft in Google Docs. I only started tracking changes halfway through. I suggest you take another pass, react to the changes, and sign off. Then you or @sabinevidal can migrate the proposed text into unicef/kindly-website#18

**Comment by amreenp7** [comment]
https://kindly.unicef.io/legal
