### ISSUE TITLE
Add CTA to Unicef Kindly site

### ISSUE THREAD

**Issue by amreenp7** [unicef/publicgoods-roadmap#127]
- [x] Email Mara to add CTA 
- [x] Follow-up as needed

Add a CTA Button to this page? https://www.unicef.org/innovation/kindly. My suggestion is to add it after the line “Reply to the message ….” and before the “How does it work?” section.

Similar to ![image.png](https://images.zenhubusercontent.com/60c762a1e54d16dc39b227a2/c86b6eab-1f8e-46b5-b661-681173b1d77c)

**Comment by amreenp7** [comment]
Emailed Mara. Will update as we hear more.

**Comment by amreenp7** [comment]
@lacabra: https://www.unicef.org/innovation/kindly this page now has the Contribute CTA.

**Comment by lacabra** [comment]
Looks good, thanks for tackling this issue so quickly! 💪
