### ISSUE TITLE
Concept doc (Kindly project)

### ISSUE THREAD

**Issue by amreenp7** [unicef/publicgoods-roadmap#42]
- [x] Begin drafting a concept document 

- [x] Fill it out collaboratively with GR + team (July 6)

**Comment by amreenp7** [comment]
Concept doc [here](https://docs.google.com/document/d/1OFUHEniGWv-7I50daFwymfGUt5DFC2MB3HXXBHQ1Jh0/edit?usp=sharing). 

@lacabra let me know if there is anything missing or that needs to be added. I will then share it with Ronen + Thomas S.

**Comment by lacabra** [comment]
Made minor editorial comments, looks very good, thank you! 🙏

**Comment by amreenp7** [comment]
Action items from Jul 6 meeting have been added to the concept doc. Closing this issue and creating a new one for the detailed plan.
