### ISSUE TITLE
MVP for map visualization

### ISSUE THREAD

**Issue by edil-it-them** [unicef/publicgoods-roadmap#48]
[Repository](https://github.com/Rolikasi/digital-public-goods-map), [Current Implementation](https://digital-public-goods-map.vercel.app/)

Develop a flexible reusable map component which will be suitable for Pathfinders and DPGs sections and also could be a standalone visualization with all layers of data.
  - [x] add responsiveness  
  - [x] update the design according to the [DPGa guidelines](https://drive.google.com/file/d/10Vv40tqHDsIKClKGR4no7r0WinG5NX3p/view)
  - [x] add a storytelling component
  - [x] add a ability to mix storytelling with images
  - [x] develop integration with google doc. We need an ability to parse the text from doc into structured jsons so non-technical staff can edit text for storytelling components. (Or use google spreadsheets)
  - [x] graphically show how many DGPs are implemented and developed in each country
  - [x] develop an info component with information about selected DPG
  - [x] show loading screen until data is fetched
  - [x] add linter
  - [x] show popups with information on countries
  - [x] show countries in which a good was developed
  - [x] show countries where the good has been implemented
  - [x] show countries participating in the Pathfinder activities of the Digital Public Goods Alliance (think of early adopters)
  - [x] show countries with implementations of goods part of the DPGA communities of practice: Digital Health, Climate Adaptation, Financial Inclusion
  - [x] pull data from set of JSONs
  - [x] pull data from google spreadsheets

**Comment by edil-it-them** [comment]
- [x] implement [Incremental Static Regeneration](https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation) so data will be fetched and processed on build once and refetched every X seconds (to handle changes from gdoc and unicef-candidates)

**Comment by edil-it-them** [comment]
[MVP](https://digital-public-goods-map.vercel.app/) is ready! 🚀
[Repository](https://github.com/Rolikasi/digital-public-goods-map)

**Comment by lacabra** [comment]
The MVP is looking awesome! 🙌 
Congratulations @Rolikasi on your great work, and keep it up 🚀

Cc: @nathanfletcher

**Comment by nathanfletcher** [comment]
I'm going ahead to close this. Thanks for the awesome work @Rolikasi 🙌🏾!
