### ISSUE TITLE
Deploy Map Visualization stories into Pathfinders and Registry sections

### ISSUE THREAD

**Issue by edil-it-them** [unicef/publicgoods-roadmap#50]
[Repo](https://github.com/Rolikasi/digital-public-goods-map)

After the integration of standalone Map Visualization into existing website, it will need to be used for story in pathfinders section.

- [ ] create a story and text for Pathfinders story
- [ ] Integrate map in [Pathfinders Countries section](https://digitalpublicgoods.net/what-we-do/) to improve heavy text mixing it with images (technical idea like in this [Washinghtonpost article](https://www.washingtonpost.com/graphics/2018/local/dc-riots-1968/))

- [ ] create documentation on how to update stories

**Comment by edil-it-them** [comment]
Hello @amreenp7 @nathanfletcher @lacabra 
I asked comms team about integration map visualization inside [What we do section](https://digitalpublicgoods.net/what-we-do/)
Quote from the team:
"Since the early discussions on the pathfinding map, we've lightened the reporting load for the pilots. So, it might be too much to ask ISG members and pathfinders for sufficient info to keep a stand alone map up to date. At this point, I think keeping the map linked from the pathfinding section of the What We Do page is a good stop gap. Happy to hear if others disagree here. "

Is it better to close this issue or rename it to `Link the map from the What We Do page`?

**Comment by nathanfletcher** [comment]
Great job @Rolikasi 
I will close this issue now.
