### ISSUE TITLE
Update Pathfinders data for map visualization

### ISSUE THREAD

**Issue by edil-it-them** [unicef/publicgoods-roadmap#58]
[Repository](https://github.com/Rolikasi/digital-public-goods-map), [Current implementation](https://digital-public-goods-map.vercel.app/)
I created a [google sheet document](https://docs.google.com/spreadsheets/d/1t75gYVhdUjPD1532DbPYN49FLXFhpRwEBFiS4Hbk6_Q) where data related to Pathfinders activities is stored. 
[Current map](https://digital-public-goods-map.vercel.app/) pulls this data and creates filter for countries where `Status` is `Confirmed` or `Exploratory`. When you click on each country you can see its `Status`, `Sector` and `Comments`.

- [x] Update data in `Pathfinder` page

**Comment by nathanfletcher** [comment]
The current data can be gotten from @Ibrahim. This is a note to check in with him for the latest updates to the data so it can be synchronized with the [google sheet documentation](https://docs.google.com/spreadsheets/d/1t75gYVhdUjPD1532DbPYN49FLXFhpRwEBFiS4Hbk6_Q)
