### ISSUE TITLE
Migration of DPG repos from UNICEF to DPGA

### ISSUE THREAD

**Issue by lacabra** [unicef/publicgoods-roadmap#60]
- [X] Write blog post
- [x] Migrate DPG-related repositories from UNICEF to DPGA
- [x] Update git URLs in CI integrations

**Comment by lacabra** [comment]
Blog article drafted

**Comment by lacabra** [comment]
This has finally been completed 🥳

**Comment by nathanbaleeta** [comment]
> This has finally been completed partying_face

Thank you @lacabra! Kudos on getting this done successfully before the close of 2021. Happy New Year!
