### ISSUE TITLE
Draft plan for DPG registry improvement (categorization)

### ISSUE THREAD

**Issue by amreenp7** [unicef/publicgoods-roadmap#65]
- [x] Meet with Praj to provide an update
- [x] Discuss best approach to move forward (i.e. draft a plan)
- [x] Distribute responsibilities

**Comment by lacabra** [comment]
@amreenp7 Not directly related (and one could argue this would be "scope creep" to what this issue is about, but for your consideration: unicef/publicgoods-candidates#615

**Comment by amreenp7** [comment]
Praj and I have created a concept note with our overall plan. We will complete this concept note + a timeline by Thurs EOD. 

https://docs.google.com/document/d/1f5jwTDSdRgmZBniaJZttBRIC6L7A6B0H1h7vfvKuYmM/edit#
