### ISSUE TITLE
Technical Assistance: SafeYou

### ISSUE THREAD

**Issue by amreenp7** [unicef/publicgoods-roadmap#73]
An exploratory conversation between SafeYou and UNICEF surface opportunities for UNICEF to assist that team with technical assistance around the creation of an open source community to drive contributions to their product to maximize the reach and impact of their solution.

9/15/21 - Introductory email to discuss the OS archetype they fit into (bathwater), and switching to Rocket Ship to Mars, and suggesting team to move development to GitHub
9/21/21 - Follow-Up to the above, awaiting response.

**Comment by amreenp7** [comment]
@lacabra to check in with ibrahim on someting re: to this.

**Comment by lacabra** [comment]
Closing, we will not pursue this any longer.
